# Generated by Django 3.2.4 on 2021-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
