# Generated by Django 3.2.4 on 2021-06-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_pwd_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('money', models.IntegerField(verbose_name='付费金额')),
                ('play_time', models.TimeField()),
            ],
        ),
    ]
