# Generated by Django 3.2.4 on 2021-06-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='play_time',
            field=models.DateTimeField(),
        ),
    ]
