# Generated by Django 3.2.4 on 2021-06-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_customer_play_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='money',
            field=models.IntegerField(default=0, verbose_name='付费金额'),
        ),
    ]
