# Generated by Django 3.2.4 on 2021-06-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_customer_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='addr',
            field=models.CharField(default='北京', max_length=64, verbose_name='家庭住址'),
            preserve_default=False,
        ),
    ]
