# Generated by Django 3.2.4 on 2021-06-30 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_tis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 9, 13, 37, 798028, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(default='', max_length=128),
        ),
    ]
