# Generated by Django 3.2.4 on 2021-07-01 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_tis_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tis',
            name='operator_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 6, 55, 23, 688673, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
