# Generated by Django 3.2.4 on 2021-07-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_tis_operator_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tis',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.user'),
        ),
    ]
