# Generated by Django 3.2.4 on 2021-07-01 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_tis_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tis',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.customer'),
        ),
        migrations.AlterField(
            model_name='tis',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.user'),
            preserve_default=False,
        ),
    ]
