# Generated by Django 3.2.4 on 2021-07-02 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210701_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 6, 33, 33, 667936, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
