# Generated by Django 3.2.4 on 2021-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_customer_play_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='play_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
