# Generated by Django 3.2.4 on 2021-07-02 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_customer_play_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="格式：'+999999999'. 最多15位数.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
