# Generated by Django 3.2.4 on 2021-06-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='提交方式名')),
                ('method', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': '提交方式表',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('parameter', models.CharField(max_length=16, verbose_name='参数名')),
                ('value', models.CharField(max_length=16, verbose_name='参数值')),
            ],
            options={
                'verbose_name_plural': '详细操作表',
            },
        ),
        migrations.CreateModel(
            name='Hooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='名称')),
                ('func_name', models.CharField(max_length=16, verbose_name='函数名')),
            ],
            options={
                'verbose_name_plural': '钩子函数表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='菜单名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyPermission.menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='角色名称')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('is_re', models.BooleanField(choices=[(0, 'url不使用正则表达式'), (1, 'url使用正则表达式')], default=0)),
                ('url', models.CharField(max_length=64, verbose_name='URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='EasyPermission.menu')),
            ],
            options={
                'verbose_name_plural': 'url表',
            },
        ),
        migrations.CreateModel(
            name='Action2Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Action2Permission', to='EasyPermission.action')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Action2Permission', to='EasyPermission.permission')),
            ],
            options={
                'verbose_name_plural': '权限表',
                'unique_together': {('action', 'permission', 'action')},
            },
        ),
        migrations.CreateModel(
            name='User2Action2Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_time', models.DateField(blank=True, default=None, null=True, verbose_name='有效时间（默认为永久有效）')),
                ('is_del', models.BooleanField(default=0, verbose_name='到期时是否自动删除')),
                ('is_menu', models.BooleanField(default=1, verbose_name='是否加入菜单')),
                ('action2Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2action2permission', to='EasyPermission.action2permission', verbose_name='权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2action2permission', to='web.user')),
            ],
            options={
                'verbose_name_plural': '用户分配权限',
                'unique_together': {('user', 'action2Permission')},
            },
        ),
        migrations.CreateModel(
            name='Role2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role2user', to='EasyPermission.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role2user', to='web.user')),
            ],
            options={
                'verbose_name_plural': '用户分配角色',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Role2Action2Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_time', models.DateField(blank=True, default=None, null=True, verbose_name='有效时间（默认为永久有效）')),
                ('is_del', models.BooleanField(default=0, verbose_name='到期时是否自动删除')),
                ('is_menu', models.BooleanField(default=1, verbose_name='是否加入菜单')),
                ('action2Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role2action2permission', to='EasyPermission.action2permission', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role2action2permission', to='EasyPermission.role', verbose_name='角色')),
            ],
            options={
                'verbose_name_plural': '角色分配权限',
                'unique_together': {('role', 'action2Permission')},
            },
        ),
        migrations.CreateModel(
            name='Action2Permission2Hooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action2Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action2permission2hooks', to='EasyPermission.action2permission', verbose_name='权限')),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action2permission2hooks', to='EasyPermission.hooks', verbose_name='钩子函数')),
            ],
            options={
                'verbose_name_plural': '权限分配钩子表',
                'unique_together': {('action2Permission', 'hook')},
            },
        ),
        migrations.CreateModel(
            name='Action2Permission2Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action2Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action2permission2detail', to='EasyPermission.action2permission')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action2permission2detail', to='EasyPermission.detail')),
            ],
            options={
                'verbose_name_plural': '权限请求参数表',
                'unique_together': {('action2Permission', 'detail')},
            },
        ),
    ]
